spring:
  #mariaDB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/portfolio?useUnicode=true&amp;characterEncoding=utf-8
    username: admin
    password: admin
    #test DB
    tomcat:
      test-on-borrow: true
      #test QUERY
      validationQuery: SELECT 1
  #Encoding UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  #messageSource
  messages:
    encoding: UTF-8
    basename: i18n/exception
  #Spring data jpa
  jpa:
    show-sql: true
  #jwt_key  
  jwt:
    secret: EpikHigh
##logback
logging:
  config: classpath:logback/logback-spring.xml
#ServerConfig
server:
  port: 5000
  
    