DROP TABLE PROJECTIMG;
DROP TABLE PROJECTSKILL;
DROP TABLE PROJECT;
DROP TABLE USERSKILL;
DROP TABLE SKILL;
DROP TABLE SKILLCLS;
DROP TABLE USERAUTH;
DROP TABLE AUTHORITY;
DROP TABLE USER;

CREATE TABLE USER
(
   USER_MAIL    VARCHAR(20),
   USER_PASS    VARCHAR(500),
   USER_NM      VARCHAR(10),
   USER_TEL     VARCHAR(12),
   USER_ADD     VARCHAR(50),
   PRIMARY KEY(USER_MAIL)
);

CREATE TABLE AUTHORITY
(
   AUTH_ID      VARCHAR(20),
   AUTH_NAME    VARCHAR(20),
   PRIMARY KEY(AUTH_ID)
);

CREATE TABLE USERAUTH
(
   USER_MAIL    VARCHAR(20),
   AUTH_ID      VARCHAR(20),
   PRIMARY KEY(USER_MAIL, AUTH_ID),
   FOREIGN KEY(USER_MAIL) REFERENCES USER (USER_MAIL)
);

CREATE TABLE SKILLCLS
(
   SKILL_CLS_NO    CHAR(1),
   SKILL_CLS_NM    VARCHAR(20),
   PRIMARY KEY(SKILL_CLS_NO)
);

CREATE TABLE SKILL
(
   SKILL_NO        VARCHAR(5),
   SKILL_NM        VARCHAR(15),
   SKILL_CLS_NO    CHAR(1),
   SKILL_IMG       VARCHAR(20),
   PRIMARY KEY(SKILL_NO),
   FOREIGN KEY(SKILL_CLS_NO) REFERENCES SKILLCLS (SKILL_CLS_NO)
);

CREATE TABLE USERSKILL
(
   USER_MAIL    VARCHAR(20),
   SKILL_NO     VARCHAR(5),
   PRIMARY KEY(USER_MAIL, SKILL_NO),
   FOREIGN KEY(USER_MAIL) REFERENCES USER (USER_MAIL),
   FOREIGN KEY(SKILL_NO) REFERENCES SKILL (SKILL_NO)
);

CREATE TABLE PROJECT
(
   PROJ_NO       VARCHAR(5),
   PROJ_CON      VARCHAR(200),
   PROJ_START    DATE,
   PROJ_END      DATE,
   PROJ_DATE     DATE,
   PRIMARY KEY(PROJ_NO)
);

CREATE TABLE PROJECTSKILL
(
   PROJ_NO     VARCHAR(5),
   SKILL_NO    VARCHAR(5),
   PRIMARY KEY(PROJ_NO, SKILL_NO),
   FOREIGN KEY(PROJ_NO) REFERENCES PROJECT (PROJ_NO),
   FOREIGN KEY(SKILL_NO) REFERENCES SKILL (SKILL_NO)
);

CREATE TABLE PROJECTIMG
(
   PROJ_IMG_NO      VARCHAR(5),
   PROJ_NO          VARCHAR(5),
   PROJ_IMG_NM      VARCHAR(50),
   PROJ_IMG_SAV     VARCHAR(100),
   PROJ_IMG_TYPE    VARCHAR(10),
   PROJ_IMG_SIZE    MEDIUMINT,
   PROJ_IMG_DATE    DATE,
   PRIMARY KEY(PROJ_IMG_NO),
   FOREIGN KEY(PROJ_NO) REFERENCES PROJECT (PROJ_NO)
);